### ISSUE TITLE
Gas limit not detected by ZilPay in some cases

### ISSUE THREAD

**Issue by bb111189** [Zilliqa/neo-savant#123]
**Describe the bug**
In some cases, the gas limit is not detected by ZilPay

**To Reproduce**
1. Deploy a large contract with small gas or default gas limit. Make sure gas limit is insufficient
2. Modify the gas limit on IDE and re-trigger ZilPay
3. ZilPay gas limit does not reflect the new gas limit 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by noel-yoo** [comment]
I think this is an UX issue. Here are my observation and screen recording.

https://user-images.githubusercontent.com/86328181/134451709-36006804-800c-4b46-9d45-06e4176142ea.mov

In the recording, the key difference is If I close the previous popup or not by clicking the “reject” button.
You can check the popup count in the top-right Zilpay icon.

If I don’t close the previous window by clicking the “reject” button, I will see the previous window without the error display. 

It makes a user possibly to think the gas price changed to previous value.

**Comment by noel-yoo** [comment]
https://github.com/zilpay/zil-pay/issues/52
